name: file_encryptor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  file_picker: 4.6.1
  file_cryptor: 0.0.3
  path_provider: 2.0.11
  material_design_icons_flutter: 5.0.6996
  google_fonts: 3.0.1
  flutter_launcher_icons: 0.9.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/encrypt icon.png"
  image_path_ios: "assets/images/encrypt icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/encrypt icon.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

